"""empty message

Revision ID: 057b4eb38a15
Revises: f91435e35407
Create Date: 2019-02-08 07:24:14.077259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057b4eb38a15'
down_revision = 'f91435e35407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Departments')
    op.drop_table('Employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.TEXT(), nullable=True),
    sa.Column('cnic', sa.TEXT(), nullable=True),
    sa.Column('qualification', sa.TEXT(), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['Departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('Departments',
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    # ### end Alembic commands ###
